### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by wipfli** [loeli-style/loeli-style#10]
Loli Style comes from the Swiss German word "Löli" which is a person who is not completely serious, or a bit of an idiot in a mild way.

Turns out that loli is has a different meaning in English: https://www.google.com/search?q=loli

We could change the name to "luhli" which sounds actually quite close to "Löli"...

**Comment by wipfli** [comment]
Or "Lulli"

**Comment by wipfli** [comment]
Loeli it is

**Comment by maxammann** [comment]
This needs some renaming: https://github.com/loeli-style/loeli-style/pull/8
