### ISSUE TITLE
Which font?

### ISSUE THREAD

**Issue by wipfli** [loeli-style/loeli-style#6]
I think the most important question when it comes to a map is the font. Which font should we use?

**Comment by wipfli** [comment]
I would vote for Noto Sans because it fits the concept of our Löli Style of being not the best font ever but gets you quite far. 

https://fonts.google.com/noto/specimen/Noto+Sans

**Comment by maxammann** [comment]
Absolutely! Noto seems like a good pick for a not so great map, which just works everywhere!

**Comment by wipfli** [comment]
Good Noto it is
